"""Every `make` command in the documentation must be a real target.

A template is read by people who type what it says, and then by every project generated from it. A command that
does not exist wastes their time and, worse, makes them doubt the parts that do
work.

Ported from fire 2026-08-19, where the same sweep found 91 broken commands.
This repository is where their names came FROM, so the failure here would be a
different one: a command designed and never built, or renamed without the docs
following.

WHY THIS IS FIDDLIER THAN IT LOOKS

English contains the word "make". "make sure", "make it" and "decisions this
makes" all match a naive pattern, so the sweep only considers lines that begin
with `make`, strips shell comments, consumes `-C <dir>` (or the DIRECTORY reads
as the target), and ignores `<placeholder>` forms. All four rules were added
because a real line in real documentation defeated the previous version.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
REPRO_LIB = REPO_ROOT / "lib/repro-tools/src/repro_tools/lib"
MAKEFILES = [
    REPO_ROOT / "Makefile",
    REPO_ROOT / "env" / "Makefile",
    REPRO_LIB / "common.mk",
    REPRO_LIB / "stata.mk",
]

# Files that are proposals or historical records rather than instructions.
NOT_INSTRUCTIONS: set[str] = set()

# Empty, and it should stay that way.
#
# fire needed this: 91 of its documented commands name analyses that do not
# exist, because its docs were written using THIS template's example names
# (price_base, remodel_base) while its own analyses are called price, remodel
# and so on. See fire's notes/documented-command-backlog.md.
#
# The template is the source of those names, so they are correct here. An entry
# appearing in this set means a command was documented and never built, and it
# should come with a note explaining why it is not simply fixed.
KNOWN_STALE_ANALYSIS_NAMES: set[str] = set()


# Tutorial placeholders: names the READER supplies. "Add a study called
# my_new_study, then run `make my_new_study`" is correct instruction, not a
# broken command, and the target exists once they have done the first half.
PLACEHOLDER_NAMES = {
    "my_analysis",
    "my_new_analysis",
    "my_new_study",
    "my_study",
    "custom",
    "detailed_analysis",
    "your_analysis",
    # docs/makefile_improvements.md walks through ADDING an analysis called
    # income_base; the command is correct once the reader has done that.
    "income_base",
}


def defined_targets() -> set[str]:
    names: set[str] = set()
    for path in MAKEFILES:
        if not path.is_file():
            continue
        for line in path.read_text().splitlines():
            if line.startswith("\t") or line.lstrip().startswith("#"):
                continue
            if line.startswith(".PHONY:"):
                names.update(line.split(":", 1)[1].split())
                continue
            match = re.match(r"^([A-Za-z0-9_.\-/ $()%]+):(?!=)", line)
            if match:
                names.update(match.group(1).split())

            # Targets generated by $(foreach ...)/$(eval $(call ...)) are not
            # literal `name:` lines, so they are invisible to the scan above.
            # project_template builds one rule per entry in ANALYSES that way,
            # which made every real analysis look undefined.
            variable = re.match(r"^(ANALYSES|STUDIES)\s*:?=\s*(.+)$", line)
            if variable:
                names.update(variable.group(2).split())
    return names


def covered(target: str, defined: set[str]) -> bool:
    if target in defined:
        return True
    for pattern in (t for t in defined if "%" in t):
        prefix, _, suffix = pattern.partition("%")
        if (
            target.startswith(prefix)
            and target.endswith(suffix)
            and len(target) > len(prefix) + len(suffix)
        ):
            return True
    return False


def commands_in(path: Path) -> set[str]:
    """`make <target>` occurrences that are commands rather than prose."""
    found: set[str] = set()
    in_block = False
    continuing_install = False
    for line in path.read_text().splitlines():
        if line.strip().startswith("```"):
            in_block = not in_block
            continue
        # Shell comments inside a code block are prose, not commands. Without
        # this, "# Let make decide based on CPU cores" and "# Symlinks make
        # paths simple" were read as invocations of targets `decide` and
        # `paths`, and a diagram asking "What's the make error?" as `error`.
        line = line.split("#", 1)[0]
        stripped = line.strip().lstrip("$").strip()
        # The line must LOOK like a command, in or out of a code block. Scanning
        # every line inside a block also read an ASCII troubleshooting diagram
        # -- "What's the make error?" -- as a target named `error`.
        # `apt-get install make git curl` is a package LIST, not a command that
        # runs make. This has to come BEFORE the "looks like a command" filter
        # below: in TEMPLATE_USAGE.md's Dockerfile the install begins on the
        # previous line and continues with a backslash, so the line that
        # mentions make does not itself say apt-get. Checking after the filter
        # meant the install line was skipped before it could be remembered --
        # my own ordering bug, and the third one this parser has had.
        if re.search(r"\b(apt-get|apt|yum|dnf|apk|brew)\b.*\binstall\b", line):
            continuing_install = line.rstrip().endswith("\\")
            continue
        if continuing_install:
            continuing_install = line.rstrip().endswith("\\")
            continue
        if not stripped.startswith("make "):
            continue
        # `make -C <dir> <target>` takes a DIRECTORY before the target, so the
        # option-skipping below has to consume it. Without that, `make -C
        # build-data all` was read as a target named `build-data`.
        for match in re.finditer(
            r"\bmake\s+(?:-C\s+\S+\s+|-[A-Za-z]\S*\s+)*([a-z][A-Za-z0-9_-]{2,})",
            line,
        ):
            target = match.group(1)
            # Placeholders like `make housing-<name>` document a FORM, not a
            # command; BASELINE.md uses exactly that.
            if line[match.end() :].startswith("<") or target.endswith("-"):
                continue
            found.add(target)
    return found


def documentation_files() -> list[Path]:
    files = sorted(REPO_ROOT.glob("*.md")) + sorted((REPO_ROOT / "docs").glob("*.md"))
    return [f for f in files if f.name not in NOT_INSTRUCTIONS]


def test_the_sweep_finds_commands():
    """Guard the guard: a parser finding nothing would pass everything."""
    total = sum(len(commands_in(f)) for f in documentation_files())
    assert total >= 10, f"only {total} make commands found across the docs"


def test_targets_are_defined():
    """Enough targets must be parsed for the comparison to mean anything."""
    defined = defined_targets()
    assert len(defined) > 50, f"only {len(defined)} targets parsed"
    assert "environment" in defined and "check-baseline" in defined


@pytest.mark.parametrize("doc", documentation_files(), ids=lambda p: p.name)
def test_every_documented_make_command_exists(doc):
    defined = defined_targets()
    missing = sorted(
        t
        for t in commands_in(doc)
        if not covered(t, defined)
        and t not in KNOWN_STALE_ANALYSIS_NAMES
        and t not in PLACEHOLDER_NAMES
    )
    assert not missing, (
        f"{doc.name} documents make target(s) that do not exist: {missing}\n"
        f"Someone will type these."
    )


def test_proposal_files_are_marked_as_such():
    """A design doc read as instructions is the failure this class produces.

    JOURNAL_PACKAGE_ENHANCEMENTS.md describes targets that were never built. It
    is excluded from the sweep above, so it must say clearly that it is not
    documentation -- otherwise the exclusion silently licenses it to mislead.
    """
    for name in NOT_INSTRUCTIONS:
        path = REPO_ROOT / name
        if not path.is_file():
            continue
        head = path.read_text()[:600]
        assert "PROPOSAL" in head.upper() or "not documentation" in head.lower(), (
            f"{name} is exempt from the command sweep but does not say it is a "
            f"proposal rather than instructions"
        )


@pytest.mark.skipif(
    not KNOWN_STALE_ANALYSIS_NAMES,
    reason="nothing is exempted, so there is nothing to document",
)
def test_the_known_stale_list_is_documented():
    """A declared exception must point at the record explaining it.

    Otherwise the allowlist becomes a place to hide things, which is the
    failure mode it exists to avoid.
    """
    note = REPO_ROOT / "notes" / "documented-command-backlog.md"
    assert note.is_file(), "notes/documented-command-backlog.md is missing"
    text = note.read_text()
    for name in KNOWN_STALE_ANALYSIS_NAMES:
        assert name in text, f"{name} is exempted but not explained in the note"


def test_known_stale_names_really_are_undefined():
    """Guard the guard: an exemption for a target that EXISTS is dead weight.

    If someone adds a `price_base` target, this fails and the entry should come
    off the list rather than sit there implying a problem that is fixed.
    """
    defined = defined_targets()
    fixed = sorted(t for t in KNOWN_STALE_ANALYSIS_NAMES if covered(t, defined))
    assert not fixed, (
        f"these are exempted but now resolve, so remove them from "
        f"KNOWN_STALE_ANALYSIS_NAMES: {fixed}"
    )
